### ISSUE TITLE
Unable to run "license-plist" command in Pods with error "dyld: Symbol not found:" after upgrading v2.3.0

### ISSUE THREAD

**Issue by imaizume** [mono0926/LicensePlist#103]
## Summary

After upgrading to v2.3.0 or later, running "licence-plist" command suddenly fails with following error message

```
dyld: Symbol not found: _$s15_ObjectiveCTypes01_A11CBridgeablePTl
  Referenced from: /path/to/project/Pods/LicensePlist/license-plist
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /path/to/project/Pods/LicensePlist/license-plist
zsh: abort      ./Pods/LicensePlist/license-plist
```

## What I did

- add line `pod 'LicensePlist'` to my `Podfile`
- `pod install` and `Podfile.lock` says "- LicensePlist (2.3.0)" or later (which ever version results same)
- In terminal, `cd` to my project root and run `./Pods/LicensePlist/license-plist`
- Then fails with message I've shown above

## Specs

- XCode: 10.1 (10B61)
- Swift version: 4.2
- Pod version: 1.6.1

I have no idea what's wrong so help me 💦

**Comment by imaizume** [comment]
I made sure that it worked well with v2.1.0.

**Comment by mono0926** [comment]
After 2.3.0, I released the tool with Xcode 10.2, and I think it was the cause.

I've released [2.4.0](https://github.com/mono0926/LicensePlist/releases/tag/2.4.0) with Xcode 10.1, so the problem will be fixed.
Could you try it?

**Comment by imaizume** [comment]
v2.4.0 works well ❗️  Thanks 👍

**Comment by mono0926** [comment]
🎉
